### ISSUE TITLE
when the project is done then will you also add support for custom extentions from turbowarp?

### ISSUE THREAD

**Issue by GaypataponALT** [scratchcpp/libscratchcpp#603]
I love how you guys are making a scratch player for c++, it could be very useful to be able to port scratch games to game consoles like the PS3/PS4 or even xbox, I wondered if you will add support for custom extentions made by other people

**Comment by adazem009** [comment]
> I love how you guys are making a scratch player for c++, it could be very useful to be able to port scratch games to game consoles like the PS3/PS4 or even xbox, I wondered if you will add support for custom extentions made by other people

Yes, I've been designing the API with (C++) extension support in mind since I started working on this. The problem is that I don't know how the extensions can be distributed.

**Comment by GaypataponALT** [comment]
> > I love how you guys are making a scratch player for c++, it could be very useful to be able to port scratch games to game consoles like the PS3/PS4 or even xbox, I wondered if you will add support for custom extentions made by other people
> 
> Yes, I've been designing the API with (C++) extension support in mind since I started working on this. The problem is that I don't know how the extensions can be distributed.

Will it also be possible to be able to compile it from scratch to any c code to consoles? I would love making games for my jailbroken ps3

**Comment by GaypataponALT** [comment]
I think you can go to the turbowarp github page and try to look at the codes for the extentions, I know that its possible to code your own extentions and use it, maybe try asking the creator of turbowarp if its possible

**Comment by adazem009** [comment]
> > > I love how you guys are making a scratch player for c++, it could be very useful to be able to port scratch games to game consoles like the PS3/PS4 or even xbox, I wondered if you will add support for custom extentions made by other people
> > 
> > Yes, I've been designing the API with (C++) extension support in mind since I started working on this. The problem is that I don't know how the extensions can be distributed.
> 
> Will it also be possible to be able to compile it from scratch to any c code to consoles? I would love making games for my jailbroken ps3

My player doesn't compile to C, but to my own bytecode format which is now deprecated since I'm working on a new compiler that uses LLVM. So it will compile to machine code.
I think the core part (libscratchcpp) would run fine (without any graphics), but I'm not sure if the Qt-based application would be able to run on the PS3.

**Comment by GaypataponALT** [comment]
Oh, then what about nintendo consoles like the wii, ds, or 3ds? maybe even the nintendo switch

**Comment by adazem009** [comment]
> I think you can go to the turbowarp github page and try to look at the codes for the extentions, I know that its possible to code your own extentions and use it, maybe try asking the creator of turbowarp if its possible

Scratch and TurboWarp are written in JavaScript which is interpreted, so it's pretty simple to implement extension support.

My player is written in C++ which is a compiled language. That means I will probably need extensions in source form and then make the application compile them. That would also mean the app size would increase because of the C++ compiler.

Another option would be to compile each extension for multiple platforms and CPU architectures, but I'd rather avoid that.

I think the best option, since I'm already using LLVM, is to compile extensions to LLVM bitcode and then compile it to machine code using LLVM.

**Comment by adazem009** [comment]
> Oh, then what about nintendo consoles like the wii, ds, or 3ds? maybe even the nintendo switch

That depends on whether the Qt framework supports these platforms.

**Comment by adazem009** [comment]
@GaypataponALT I misread the title, if you mean extensions that were made for TurboWarp, then no because they're written in JavaScript. It would mean I would have to write JavaScript wrappers for the C++ API and make it compatible with the TurboWarp API which I'm not planning to do as of right now.
If you have further questions, feel free to ask.
